/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

/* automatically generated by rust-bindgen */

use jsapi::{JSContext, JSHandleObject, JSHandleId, JSPropertyDescriptor, JSMutableHandleValue};
use jsapi::{JSTracer, JSFunction, JSNative, JSErrorFormatString, JSFreeOp, JSMutableHandleObject};
use jsapi::{JSClass, JSString, JSObject, jsid, JSVersion, JSHandleValue, JSTraceOp};
use jsapi::{Enum_OnNewGlobalHookOption, JSPrincipals, Enum_JSType};
use jsfriendapi::JSJitInfo;
use jsval::JSVal;
use libc;

pub type c_bool = libc::c_int;
pub type JSBool = c_bool;

pub struct JSMutableHandle<T> {
    pub unnamed_field1: *mut *mut T,
}

pub struct ProxyTraps {
    pub preventExtensions: Option<extern "C" fn(*mut JSContext, JSHandleObject) -> c_bool>,
    pub getPropertyDescriptor: Option<extern "C" fn(*mut JSContext, JSHandleObject, JSHandleId, JSMutableHandle<JSPropertyDescriptor>, u32) -> c_bool>,
    pub getOwnPropertyDescriptor: Option<extern "C" fn(*mut JSContext, JSHandleObject, JSHandleId, JSMutableHandle<JSPropertyDescriptor>, u32) -> c_bool>,
    pub defineProperty: Option<extern "C" fn(*mut JSContext, JSHandleObject, JSHandleId, JSMutableHandle<JSPropertyDescriptor>) -> c_bool>,
    pub getOwnPropertyNames: *u8, //XXX need a representation for AutoIdVector&
    pub delete_: Option<extern "C" fn(*mut JSContext, JSHandleObject, JSHandleId, *mut bool) -> JSBool>,
    pub enumerate: *u8, //XXX need a representation for AutoIdVector&

    pub has: Option<extern "C" fn(*mut JSContext, JSHandleObject, JSHandleId, *mut JSBool) -> JSBool>,
    pub hasOwn: Option<extern "C" fn(*mut JSContext, JSHandleObject, JSHandleId, *mut c_bool) -> c_bool>,
    pub get: Option<extern "C" fn(*mut JSContext, JSHandleObject, JSHandleObject, JSHandleId, JSMutableHandleValue) -> c_bool>,
    pub set: Option<extern "C" fn(*mut JSContext, JSHandleObject, JSHandleObject, JSHandleId, JSBool, JSMutableHandleValue) -> JSBool>,
    pub keys: *u8, //XXX need a representation for AutoIdVector&
    pub iterate: Option<extern "C" fn(*mut JSContext, JSHandleObject, uint, JSMutableHandleValue) -> JSBool>,

    pub isExtensible: Option<extern "C" fn(*mut JSContext, JSHandleObject, *mut c_bool) -> c_bool>,
    pub call: Option<extern "C" fn(*mut JSContext, JSHandleObject, uint, JSMutableHandleValue) -> JSBool>,
    pub construct: Option<extern "C" fn(*mut JSContext, JSHandleObject, uint, JSMutableHandleValue, JSMutableHandleValue) -> JSBool>,
    pub nativeCall: *u8, //XXX need a representation for IsAcceptableThis, NativeImpl, and CallArgs
    pub hasInstance: Option<extern "C" fn(*mut JSContext, JSHandleObject, JSMutableHandleValue, *mut JSBool) -> JSBool>,
    pub objectClassIs: Option<extern "C" fn(JSHandleObject, uint, *mut JSContext) -> JSBool>, //XXX ESClassValue enum
    pub fun_toString: Option<extern "C" fn(*mut JSContext, JSHandleObject, uint) -> *JSString>,
    //regexp_toShared: *u8,
    pub defaultValue: Option<extern "C" fn(*mut JSContext, JSHandleObject, Enum_JSType, JSMutableHandleValue) -> JSBool>, //XXX JSType enum
    pub finalize: Option<extern "C" fn(*mut JSFreeOp, *mut JSObject)>,
    pub getPrototypeOf: Option<extern "C" fn(*mut JSContext, JSHandleObject, JSMutableHandleObject) -> c_bool>,
    pub trace: Option<extern "C" fn(*mut JSTracer, *mut JSObject)>
}

#[link(name = "jsglue")]
extern { }


#[cfg(target_os = "android")]
#[link_args = "-ljsglue -lstdc++ -lgcc -rdynamic"]
extern { }

extern {

//#[rust_stack]
pub fn RUST_JS_NumberValue(d: f64) -> JSVal;

//#[rust_stack]
pub fn CallJitSetterOp(info: *JSJitInfo, cx: *mut JSContext, thisObj: JSHandleObject, specializedThis: *libc::c_void, vp: *mut JSVal) -> c_bool;

pub fn CallJitGetterOp(info: *JSJitInfo, cx: *mut JSContext, thisObj: JSHandleObject, specializedThis: *libc::c_void, vp: *mut JSVal) -> c_bool;

//#[rust_stack]
pub fn CallJitMethodOp(info: *JSJitInfo, cx: *mut JSContext, thisObj: JSHandleObject, specializedThis: *libc::c_void, argc: libc::c_uint, vp: *mut JSVal) -> c_bool;

//#[rust_stack]
pub fn RUST_FUNCTION_VALUE_TO_JITINFO(v: JSVal) -> *JSJitInfo;

pub fn SetFunctionNativeReserved(fun: JSHandleObject, which: libc::size_t, val: *JSVal);
pub fn GetFunctionNativeReserved(fun: JSHandleObject, which: libc::size_t) -> *JSVal;

pub fn CreateProxyHandler(traps: *ProxyTraps, extra: *libc::c_void) -> *libc::c_void;
pub fn CreateWrapperProxyHandler(traps: *ProxyTraps) -> *libc::c_void;
pub fn NewProxyObject(cx: *mut JSContext, handler: *libc::c_void, priv_: *JSVal,
                      proto: JSHandleObject, parent: JSHandleObject, call: JSHandleObject,
                      construct: JSHandleObject) -> *mut JSObject;
pub fn WrapperNew(cx: *mut JSContext, obj: JSHandleObject, parent: JSHandleObject, handler: *libc::c_void) -> *mut JSObject;

pub fn GetProxyExtra(obj: JSHandleObject, slot: libc::c_uint) -> JSVal;
pub fn GetProxyPrivate(obj: JSHandleObject) -> JSVal;
pub fn SetProxyExtra(obj: JSHandleObject, slot: libc::c_uint, val: JSVal);

pub fn GetObjectProto(cx: *mut JSContext, obj: JSHandleObject, proto: JSMutableHandleObject) -> c_bool;
pub fn GetObjectParent(obj: *mut JSObject) -> *mut JSObject;

pub fn RUST_JSID_IS_INT(id: JSHandleId) -> c_bool;
pub fn RUST_JSID_TO_INT(id: JSHandleId) -> libc::c_int;
pub fn RUST_JSID_IS_STRING(id: JSHandleId) -> c_bool;
pub fn RUST_JSID_TO_STRING(id: JSHandleId) -> *mut JSString;

pub fn RUST_SET_JITINFO(func: *mut JSFunction, info: *mut JSJitInfo);

pub fn RUST_INTERNED_STRING_TO_JSID(cx: *mut JSContext, str: *mut JSString) -> jsid;

pub fn DefineFunctionWithReserved(cx: *mut JSContext, obj: JSHandleObject,
                                  name: *libc::c_char, call: JSNative, nargs: libc::c_uint,
                                  attrs: libc::c_uint) -> *mut JSObject;
pub fn GetObjectJSClass(obj: JSHandleObject) -> *mut JSClass;
pub fn RUST_js_GetErrorMessage(userRef: *libc::c_void, locale: *libc::c_char,
                               errorNumber: libc::c_uint) -> *mut JSErrorFormatString;
pub fn js_IsObjectProxyClass(obj: *mut JSObject) -> bool;
pub fn js_IsFunctionProxyClass(obj: *mut JSObject) -> bool;
pub fn IsProxyHandlerFamily(obj: JSHandleObject) -> bool;
pub fn GetProxyHandlerExtra(obj: JSHandleObject) -> *libc::c_void;
pub fn GetProxyHandler(obj: JSHandleObject) -> *libc::c_void;
pub fn InvokeGetOwnPropertyDescriptor(handler: *libc::c_void, cx: *mut JSContext, proxy: JSHandleObject, id: JSHandleId, desc: JSMutableHandle<JSPropertyDescriptor>, flags: u32) -> c_bool;
pub fn GetGlobalForObjectCrossCompartment(obj: JSHandleObject) -> *mut JSObject;
pub fn ReportError(cx: *mut JSContext, error: *libc::c_char);
pub fn IsWrapper(obj: *mut JSObject) -> JSBool;
pub fn UnwrapObject(obj: *mut JSObject, stopAtOuter: JSBool) -> *mut JSObject;

pub fn ContextOptions_SetVarObjFix(cx: *mut JSContext, enable: bool);
pub fn CompartmentOptions_SetVersion(cx: *mut JSContext, version: JSVersion);
pub fn CompartmentOptions_SetTraceGlobal(cx: *mut JSContext, op: JSTraceOp);

pub fn ToBoolean(v: JSHandleValue) -> bool;
pub fn ToString(cx: *mut JSContext, v: JSHandleValue) -> *mut JSString;
pub fn ToNumber(cx: *mut JSContext, v: JSHandleValue, out: *mut f64) -> bool;
pub fn ToUint16(cx: *mut JSContext, v: JSHandleValue, out: *mut u16) -> bool;
pub fn ToInt32(cx: *mut JSContext, v: JSHandleValue, out: *mut i32) -> bool;
pub fn ToUint32(cx: *mut JSContext, v: JSHandleValue, out: *mut u32) -> bool;
pub fn ToInt64(cx: *mut JSContext, v: JSHandleValue, out: *mut i64) -> bool;
pub fn ToUint64(cx: *mut JSContext, v: JSHandleValue, out: *mut u64) -> bool;

pub fn AddObjectRoot(cx: *mut JSContext, obj: *mut *mut JSObject) -> bool;
pub fn RemoveObjectRoot(cx: *mut JSContext, obj: *mut *mut libc::c_void);

pub fn NewGlobalObject(cx: *mut JSContext, clasp: *JSClass,
                       principals: *mut JSPrincipals,
                       hookOption: Enum_OnNewGlobalHookOption) -> *mut JSObject;

pub fn CallFunctionValue(cx: *mut JSContext, obj: JSHandleObject, fval: JSHandleValue,
                         rval: JSMutableHandleValue) -> bool;
}
