CXX ?= g++
AR ?= ar
CFLAGS += -fPIC

ifeq ($(shell $(CXX) -v 2>&1 | grep -c 'clang version\|Apple.*clang'),1)
CFLAGS += -Wno-c++0x-extensions -Wno-return-type-c-linkage -Wno-invalid-offsetof
endif

MOZJS_OUTDIR = $(shell find $(OUT_DIR)/.. -name 'mozjs-sys-*' -type d)
CFLAGS += -I$(MOZJS_OUTDIR)/dist/include

.PHONY: all
all: $(OUT_DIR)/libjsglue.a

$(OUT_DIR)/libjsglue.a: $(OUT_DIR)/jsglue.o
	$(AR) rcs $@ $^

$(OUT_DIR)/jsglue.o: src/jsglue.cpp
	$(CXX) $(CFLAGS) -fno-rtti $< -o $@ -c
